// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBju2MpX9FvjnJINiWrCnsGSAkaTS79lhY',
    appId: '1:619555565248:web:3920946dd135f0f8260725',
    messagingSenderId: '619555565248',
    projectId: 'vision-mart-cea1e',
    authDomain: 'vision-mart-cea1e.firebaseapp.com',
    storageBucket: 'vision-mart-cea1e.firebasestorage.app',
    measurementId: 'G-Y88EB1ZDZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkmqo2QMpZUiTP1BAZnSqhfLW9YvJWgqM',
    appId: '1:619555565248:android:aba596ae3375891a260725',
    messagingSenderId: '619555565248',
    projectId: 'vision-mart-cea1e',
    storageBucket: 'vision-mart-cea1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoy19rpoqyqSIyuhEatbTDX37xLRqwKfc',
    appId: '1:619555565248:ios:735fe7c3042f3c47260725',
    messagingSenderId: '619555565248',
    projectId: 'vision-mart-cea1e',
    storageBucket: 'vision-mart-cea1e.firebasestorage.app',
    iosBundleId: 'com.example.visionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoy19rpoqyqSIyuhEatbTDX37xLRqwKfc',
    appId: '1:619555565248:ios:735fe7c3042f3c47260725',
    messagingSenderId: '619555565248',
    projectId: 'vision-mart-cea1e',
    storageBucket: 'vision-mart-cea1e.firebasestorage.app',
    iosBundleId: 'com.example.visionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBju2MpX9FvjnJINiWrCnsGSAkaTS79lhY',
    appId: '1:619555565248:web:b4e9f268dcee6c11260725',
    messagingSenderId: '619555565248',
    projectId: 'vision-mart-cea1e',
    authDomain: 'vision-mart-cea1e.firebaseapp.com',
    storageBucket: 'vision-mart-cea1e.firebasestorage.app',
    measurementId: 'G-KH2MC633F0',
  );
}
